### ISSUE TITLE
Zonestatus (Byzone/landzone)

### ISSUE THREAD

**Issue by krwi-balk** [Septima/OneDoor#102]
@rastermanden @klavspc 
Jeg kunne godt tænke mig at informationen fra Plandata med udgangspunkt i 'Zonestatus' blev ændret så det blev et enten/eller svar.

Lige nu trækkes der blot fra laget på samme måde som lokalplaner og hvor der vises en række - måske især for en kommune - ubetydelige informationer som fx 'Planid'.

![Image](https://github.com/user-attachments/assets/a00852fd-1413-4320-98fd-afb61723df77)

Kunne man i stedet blot få et felt der tjekkede om søgningen var inden eller uden for byzone-grænsen? 
Og hvis der var et geometrisk hit svarede 'Byzone' og hvis der ikke var et geometrisk hit svarede 'Landzone' og at man blot kunne tjekke efter med "øjet" (knappen), hvordan afgrænsningen for byzonen ser ud.
Jeg tror at det vil gøre informationen mere kommunikerbar.

**Comment by krwi-balk** [comment]
@rastermanden Jeg er ikke helt sikker på, hvordan jeres løsning arbejder sammen med den løsning jeg beskriver?

Jeg kunne i første omgang godt tænke mig at kunne slukke 'Planid' og 'Kommune'.
Og helt ideelt vil det være, hvis 'Zonestatus' henter Byzone ved geografisk overlap og 'Landzone', hvis der ikke er et geografisk overlap.
Ved sagsbehandling så er det faktisk det faktum, at noget ligger i landzone der skaber de største komplikationer i mange sammenhænge.

**Comment by DocDemar** [comment]
Vi vil foreslå at løse det med en Zone handler, der for alle slags resultater kan vise om resultatet ligger i land- eller byzone eller i begge zoner.

det vil tage 1-2 dage at implementere
Er det noget vi skal gå videre med?

**Comment by krwi-balk** [comment]
@DocDemar 
Jeg vil gerne gå videre med det. Er det noget der kan vendes i vores brugergruppe? 
Fællesfinansiering kunne være godt.

Kunne det komme på en liste over ting til drøftelse kommunerne i mellem?

**Comment by GISAabenraa** [comment]
Vi er interesseret i Aabenraa Kommune

**Comment by Ellebjerg** [comment]
Lige denne har vi ikke den store interesse i.

**Comment by DocDemar** [comment]
@krwi-balk og @GISAabenraa 
Hvad siger I til at vi tager sagen op på erfa møde den 29. april?

**Comment by krwi-balk** [comment]
> [@krwi-balk](https://github.com/krwi-balk) og [@GISAabenraa](https://github.com/GISAabenraa) Hvad siger I til at vi tager sagen op på erfa møde den 29. april?

Meget gerne :-)

**Comment by krwi-balk** [comment]
@DocDemar 
Er dette én der arbejdes på, eller hvad blev konklusionen?

**Comment by rastermanden** [comment]
Der er en ny handler

- _type: Septima.Search.LandzoneDetailsHandler

Den slår op i temaet: pdk:theme_pdk_zonekort_v. Hvis den rammer noget, skrives der:  I landzone: Ja og ved ingen hits: I landzone: Nej

```XML
<Abstract>
Zonekortet, genereres automatisk baseret på lokalplaner og beslutninger om tilbageførsel til landzone. Zonekortet er blevet genereret automatisk siden 8/12/2021. Zoneændringer fra før dette er baseret på Zonekortudgangspunktet I denne udstilling af zonekortet er polygonerne ikke blevet føjet sammen, så det stadig er muligt at se hver enkelt polygon
</Abstract>
``

**Comment by GISAabenraa** [comment]
Hvor og hvordan skal man tilføje den nye handler for at få det testet?  Gætter at det er her ...\config\organisations\kunde\core.yml men hvad er syntaksen præcis?

**Comment by krwi-balk** [comment]
> Hvor og hvordan skal man tilføje den nye handler for at få det testet? Gætter at det er her ...\config\organisations\kunde\core.yml men hvad er syntaksen præcis?

Jeg har placeret den under 'Om husnummeret'

```  
omHusnummeret:
    _type: Septima.Search.ComposedDetailsHandler
    _options:
      targets: [{source: '*', typeId: 'adresse'}]
      meta:
        type: labelvalue
        value: 
      id: omhusnummer
      more: true
      buttonText: 'Om husnummeret'
      description: 'XXXX'
    detailhandlers:
      - _type: Septima.Search.HusnummerInfoProvider
        _options:
          geosearcher:
            _ref: $.searchers.gsearch
          fields:
            - postadresse
            - antaladdresser
            - matrikelnr
      - _type: Septima.Search.LandzoneDetailsHandler
      - _type: Septima.Search.FilarkivLinkForAdresseMatrikelHandler
 ```
<br>

<img width="829" height="595" alt="Image" src="https://github.com/user-attachments/assets/d7da8ab3-8ee3-4d07-bebc-f1441937aecd" />

**Comment by rastermanden** [comment]
```yml
  controller:
    _type: Septima.Search.Controller
    _options:
      blankBehavior: search
    searchers:
      - _ref: "$.searchers.dawa"
  searchers:
    dawa:
      _type: Septima.Search.DawaSearcher
      _options:
        minimumShowCount: 5
      detailhandlers:
        - _type: Septima.Search.LandzoneDetailsHandler
```
