### ISSUE TITLE
Ikoner på polygon-lag: Det kunne være godt, hvis ikoner på hhv. byzone og matrikler ikke blev noteret som punkt-markører, men som flader

### ISSUE THREAD

**Issue by furesoe** [Septima/OneDoor#32]
![image](https://user-images.githubusercontent.com/38730459/158435687-af354182-1c1c-4885-9190-ee316f8e4cfe.png)

**Comment by rastermanden** [comment]
Vi er igang med en løsning p.t.

**Comment by rastermanden** [comment]
Man kan nu lægge sine egne ikoner ind. Der kommer med tiden indbyggede. Man kan også ændre tekst:

``` yaml
    _type: Septima.Search.GeoSearch
    _options:
      resultTypes:
        matrikelnumre:
          singular: Matrikelnummer
          plural: Matrikelnumre
          iconURI: "assets/icons/matrikel.svg"
```
