### ISSUE TITLE
Flere små (fejl)rettelser til Produktionsenheder-searcheren

### ISSUE THREAD

**Issue by furesoe** [Septima/OneDoor#35]
- Regnskaber-fanen hedder Regnskaberbutton
- Telefonnumre bør vel ikke være hyperlinks?
- Ejendomme-fanen fejler
- Regnskaber-visningen er ikke pænt opstillet
- Mange produktionsenheder kan ikke vises i kortet, selvom adressen ligger i kommunen

![image](https://user-images.githubusercontent.com/38730459/158439551-7be6ca38-cc42-4dab-9a04-d331124cbf5c.png)

![image](https://user-images.githubusercontent.com/38730459/158439941-19c80406-84a4-45d0-aafb-e81a5bcdd8b9.png)

![image](https://user-images.githubusercontent.com/38730459/158440128-0f3f7acf-40c4-4009-a1f9-745fa1f81619.png)

![image](https://user-images.githubusercontent.com/38730459/158440453-1133835d-0ecd-4fbc-ad33-33e4af60f80c.png)

**Comment by furesoe** [comment]
@klavspc

**Comment by klavspc** [comment]
Her er tale om flere forskellige underliggende forhold - jeg assigner derfor dette issue overordnet til @KimjacSep, som er tovholder på OneDoor

Jeg har skrevet til de ansvarlige for de enkelte checkbokse nedenfor for at gøre dem opmærksomme på fejlene

- [ ] Regnskaber-fanen hedder Regnskaberbutton
- [ ] Telefonnumre bør vel ikke være hyperlinks?
- [ ] Ejendomme-fanen fejler
- [ ] Regnskaber-visningen er ikke pænt opstillet
- [ ] Mange produktionsenheder kan ikke vises i kortet, selvom adressen ligger i kommunen

**Comment by klavspc** [comment]
Ad _Ejendomme-fanen fejler_

Kan i sikre, at i kører mod produktions-api'et og ikke test, som er lukket?

Således:
```
ejerservice:
  fetcher:
    _type: ejerfortegnelse.Fetcher
    _options:
      endPoint: http://ejerservice.septima.dk/api
```

**Comment by rastermanden** [comment]
> Telefonnumre bør vel ikke være hyperlinks? 

Det kan jo diskuteres, men på mobil åbner telefonappen ved klik

**Comment by rastermanden** [comment]
Regnskaber kan konfigureres med titel på fane "buttoText" samt at kortet fjernes så det præsenteres pænere


``` yml
- _type: Septima.Search.RegnskaberForCvrNummerHandler
  _options:
    id: regnskaber
    buttonText: Regnskaber
    renderHints:
      - "nomap"
```

**Comment by furesoe** [comment]
> Ad _Ejendomme-fanen fejler_
> 
> Kan i sikre, at i kører mod produktions-api'et og ikke test, som er lukket?
> 
> Således:
> 
> ```
> ejerservice:
>   fetcher:
>     _type: ejerfortegnelse.Fetcher
>     _options:
>       endPoint: http://ejerservice.septima.dk/api
> ```

Det ser ud til at virke nu. Tak for det!

**Comment by rastermanden** [comment]
I den nye cvrsearcher (1.4.52) hentes data fra andet api og data er meget bedre geokodet. Der er dog stadig nogle hvor det er meget svært at geokode.

Konfigureres på denn emåde:

```yml
  cvr:
    _type: Septima.Search.DataApi.CvrSearcher
    _options:
      fetcher:
        _ref: $.searchers.dataApiFetcher
      goal: "*"
      kommunekode: "0167"
    detailhandlers:
    - _type: Septima.Search.DataApi.CvrInfoProvider
      _options:
        cvrSearcher:
          _ref: $.searchers.cvr

```
