### ISSUE TITLE
Fejl i CVR-visning

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#41]
Vi har en fejl i CVR-visningen på vores OneDoor. Jeg kan se, at fejlen ikke findes på https://onedoor.test.septima.dk/#/septima/lite. 

Vi kan sagtens fremsøge virksomheder og produktionsenheder, men når vi så klikker på en specifik enhed i søgeresultatet, får vi "Unexpected error. S3Error: Controller.get: could not find objekt".

Fejlen er testet med Netto som produktionsenhed og Hvidovre Kommune som virksomhed, men jeg tænker, at den er generel.

**Comment by furesoe** [comment]
@Ellebjerg , jeg synes ikke at kunne genkalde denne fejl. Vi blev opgraderet til nyest version i går.

**Comment by Ellebjerg** [comment]
@furesoe Vi har den stadig, men så er det jo nok en lokal fejl.

**Comment by klavspc** [comment]
Cvr-søgningen er under opdatering og kommer på plads i denne uge med ny version af OneDoor - info følger i dette issue om hvordan den nye cvr-søgning lægges om

**Comment by klavspc** [comment]
Tidligere blev cvr-søgning udført af cvr_enhedsSearcher eller, i sjældne tilfælde, en _redata_ searcher. Nu skal cvr-søgning bruge det nye dataapi:
Tidligere:
```
    cvrsearcher:
      #_type: Septima.Search.CVR_enhedSearcher
      #_options:
      #  searchindexToken:
      #    _ref: $.parameters.core.searchindex.token
      #  kommunekode:
      #    _ref: $.parameters.kommunekode
      #detailhandlers:
      #  - _type: Septima.Search.CvrInfoProvider
```
Nu:
```
    cvrsearcher:
      _type: Septima.Search.DataApi.CvrSearcher
      _options:
        fetcher:
          _type: Septima.Search.DataApi.Fetcher
        kommunekode:
          _ref: $.parameters.kommunekode
      detailhandlers:
        - _type: Septima.Search.DataApi.CvrInfoProvider
```
**Virksomheder for husnummer**:
Tidligere:
```
    cvrvirksomhederforhusnummer:
      #_type: Septima.Search.CvrVirksomhederForAdresseProvider
      #_options:
      #  cvr_enhedSearcher:
      #    _ref: $.core.dk.cvrsearcher
```
Nu:
```
    cvrvirksomhederforhusnummer:
      _type: Septima.Search.DataApi.CvrRegistreringerForHusnummer
      _options:
        cvrSearcher:
          _ref: $.core.dk.cvrsearcher
```
