### ISSUE TITLE
Den nye produktionsenheds-visning

### ISSUE THREAD

**Issue by furesoe** [Septima/OneDoor#42]
@klavspc @rastermanden

Det er dejligt med udbygningen af p-enheds-visningen i OneDoor.

Jeg synes dog, at der er nogle potentialer for forbedringer.

1. Der er enten for meget dobbeltkonfekt eller for dårlig beskrivelse af, hvor tilsyneladende ens info fremkommer flere gange
2. Øvrige produktionsenheder/filialer bør flyttes til en fane i toppen, så den ikke forstyrrer al øvrig data om p-enheden
3. Det kunne være godt at få udstillet antal ansatte for p-enheden - i første omgang det der interval, som ligger i CVR
4. Der fremkommer en fejlmeddelelse på branchekoden - det gælder alle de søgeresultater, jeg finder (eksempel: http://furesoeg/#/furesoe/ejendomsperspektiv/cvr/produktionsenhed/1028285066/Septima.Search.DataApi.CvrInfoProvider_0)

![image](https://user-images.githubusercontent.com/38730459/214870759-709adcf8-a256-4fea-a7f3-c5a6a2719224.png)

![image](https://user-images.githubusercontent.com/38730459/214870810-06254435-8178-4c9b-a59b-3ea7b5eda63a.png)

![image](https://user-images.githubusercontent.com/38730459/214871525-cd11fe13-55ac-4690-be78-3c1bbb8a0879.png)

**Comment by Ellebjerg** [comment]
Gode forbedringsforslag fra foresoe

**Comment by rastermanden** [comment]
Den viste detaljevisning kan frit konfigureres efter eget behov og dermed vælge hvilke felter der skal medtages:

https://onedoor.test.septima.dk/guide/Septima.Search.DataApi.CvrInfoProvider.html


Man kan også konfigure en fane for f.eks "øvrige produktionsenheder"

**Comment by rastermanden** [comment]
Eksempelopsætning
```yaml 
_type: Septima.Search.DataApi.CvrSearcher
 _options:
  kommunekode: '101'
  detailhandlers:
   - _type: Septima.Search.DataApi.CvrInfoProvider
     _options:
       fields_virksomhed: ["cvrnummer", "navn", "virksomhedstype", "formaal", "virkningsdato", "adresse", "adresse_result", "email", "tlf", "hovedbranche", "hovedafdelingkode", "hovedgruppekode", "gruppekode", "undergruppekode", "branchekode", "antalansatte","virksomhed_cvrlink", "enhedsliste"]
         fields_produktionsenhed: ["pnummer","navn", "adresse", "adresse_result", "email", "tlf", "branchekode", "cvrlink","virksomhed_navn", "virksomhed_result", "virksomhed_cvrlink", "virksomhed_enhedsliste","hovedafdelingkode", "hovedgruppekode", "gruppekode", "undergruppekode", "antalansatte"]
         virksomhed_enhedsliste_komnumre: 101 147

```
