### ISSUE TITLE
Implementér skråfoto for alle resultat-typer

### ISSUE THREAD

**Issue by klavspc** [Septima/OneDoor#47]
Er nu implementeret
Skråfoto for lokalplan:
![image](https://user-images.githubusercontent.com/3736091/221583889-288cf815-2810-4928-bab2-64b1d7376a93.png)

**Comment by klavspc** [comment]
Skråfoto kan nu bruges for alle resulta-typer

- Hvis størrelsen (extentet) er for stort vises ikke skråfoto
- option.draw er ikke relevant længere - der tegnes altid
- Eksempel på brug:
```
  _type: Septima.Search.SkraafotoProvider
  _options:
    id: skraafoto
    header: SDFE skråfotos
    token:
      _ref: $.parameters.core.skraafoto.token
```
Token fås ved aftale med Septima om brug af skråfoto
