### ISSUE TITLE
Implementér Offentlige Links for alle resultat-typer

### ISSUE THREAD

**Issue by klavspc** [Septima/OneDoor#48]
Impelementeret

Kun få af de sædvenlig offentlige links vises for resultater som _ikke_ relaterer sig til ejendom/husnummer 

Her dekoreres et punkt fra Septima's poi-service (Kræver separat aftale)

![image](https://user-images.githubusercontent.com/3736091/221588383-fd29d138-82e1-4d24-ad09-29190f86c1e9.png)

**Comment by klavspc** [comment]
Implementeret
```
 - _type: Septima.Search.OffentligeLinksProvider
   _options:
     links: ['*']
     buttonText: Offentlige links (OffentligeLinksProvider)
```
