### ISSUE TITLE
Nabo-områder kommer med i konfliktsøgning selvom de kun deler grænselinje.

### ISSUE THREAD

**Issue by MichaelDavidKnudsen** [Septima/OneDoor#5]
Er det muligt at sætte en negativ buffer på fx 10 cm på konfliktsøgningen, så man undgår at få områder med, hvor det ”bare” er grænselinjen, der deles?

![image](https://user-images.githubusercontent.com/8234702/151768000-c1048f25-fbdf-4dc7-b96b-64bd68220775.png)

**Comment by klavspc** [comment]
Vi er i gang med at gå alle søgninger igennem mhb på at rette op på dette. Det er dog ikke en negativ buffer vi er i gang med derimod at udelade geometrier, der kun "toucher"

**Comment by MichaelDavidKnudsen** [comment]
Det lyder fint, at få rettet til at udlade geometrier, der kun "toucher".
Dog vil jeg stadig mene, at en mulighed for at sætte en negativ buffer på 5-10 cm vil være gavnligt, da den fjerne fejl resultater, som følge af små digitaliseringsfejl. Dem ser vi relativt ofte.

**Comment by klavspc** [comment]
Det vil være helt op til den enkelte searcher at definere "toucher". Hvis datagrundlaget giver at der bør bruges negativ buffer eller den underliggende service ikke understøtter touches som defineret i wfs - ja, så vil en negativ buffer formodentlig være vejen frem

Vi arbejder på det

**Comment by rastermanden** [comment]
Man kan nu bruge en ny s3.SqDetailsHandler, der kan medtage en buffer på søgegeometrien. Her på 50 cm.


```yaml
    _type: s3.SqDetailsHandler
    _options:
      polygonIntersectsBuffer: -0.5
      buttonText: Planer
      noResultsListItem:
        type: labelvalue
```
