### ISSUE TITLE
Søgning på branchekoder

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#60]
Kommunens erhvervsteam har efterspurgt mulighed for at søge på branchekoder/-betegnelser i kortet. Er det noget, I kan se en relevans i at tilføje?

Vh Lars

**Comment by rastermanden** [comment]
Der ner nogle muligheder for at lave nogle opdelte brancekodesøgninger i dels søgefeltet og på kortet.

Er det nogle bestemte branckekoder (hovede?) det drejer sig om ?


Vi kan prøve at lave en opsætning for jer med udvalgte koder.

Se mere her:
https://onedoor.test.septima.dk/guide/Septima.Search.DataApi.CvrSearcher.html?highlight=cvr#options

**Comment by Ellebjerg** [comment]
Jeg ved ikke, om der er bestemte koder, de er mere interesserede i end andre. I og med, at vi har Avedøre Holme, har vi et temmelig bredt spektre af koder repræsenteret i kommunen. Og i virkeligheden er det nok mere betegnelserne end selve koderne, de er interesserede i at kunne søge i. I hvert fald spurgte de til muligheden for at søge på fx "Fødevare", "Fødevareproducenter" og lignende.
Det er heller ikke klart, om det er hovedbranche eller bibranche, de er interesserede i at kunne søge i. Formentlig er det begge dele.

**Comment by rastermanden** [comment]
Branchekoder og tekster kan findes [her](https://www.dst.dk/klassifikationsbilag/380b62f0-da15-4117-8708-0f319e8f6aad): 

Kan bruges på denne måde:


```yml
    _type: Septima.Search.DataApi.CvrSearcher
    _options:
      fetcher:
        _ref: $.searchers.dataApiFetcher
      goal: "produktionsenhed"
      kommunekode: "0101"
      hovedgruppekode: "10 11 20 21 41 42 43 47 86"
    detailhandlers:
    - _type: Septima.Search.DataApi.CvrInfoProvider
      _options:
        cvrSearcher:
          _ref: $.searchers.cvr
```

Lukker issue for nu. Hvis der er problemer med opsætning, genåbnes issue
