### ISSUE TITLE
Vedtagne Lokalplaner - Ejendomme hits afhængig af arealdækning

### ISSUE THREAD

**Issue by GISAabenraa** [Septima/OneDoor#64]
Vi har behov for at jystere hits på Ejendomme ved at definere (gennem parameter) hvor meget (arealmæssigt) skal Lokalplanen dække ejendommen før den skal med i resultatet under fanen Ejendomme.

**Comment by GISAabenraa** [comment]
**nice to have**: Størrelsen på overlappende areal burde have betydning for placeringen i resultat listen (jo større jo højere)

**Comment by rastermanden** [comment]
Man kan konfigure en bufferstørrelse 
Se mere her:

https://onedoor.test.septima.dk/guide/s3.SqDetailsHandler.html

**Comment by GISAabenraa** [comment]
Er det i **core.yml** jeg skal angive **polygonIntersectsBuffer** ?

**Comment by GISAabenraa** [comment]
![polygonIntersectsBuffer](https://github.com/Septima/OneDoor/assets/115632878/293a4107-ccee-4fc2-a476-2c0b35187deb)

**Comment by rastermanden** [comment]
Ja, erstat buffer med polygonIntersectsBuffer

optionen buffer eksisterer ikke mere

**Comment by rastermanden** [comment]
og derefter genstart service

**Comment by GISAabenraa** [comment]
> 

Skal vi opdatere?

**Comment by GISAabenraa** [comment]
Har ændret og genstartet servicen, men det har IKKE hjulpet :(  
![polygonIntersectsBuffer](https://github.com/Septima/OneDoor/assets/115632878/7a75f1c8-31ab-484d-b230-06d01e173f39)

**Comment by rastermanden** [comment]
Kan du sende mig en url til hvor du har problemet, så ser jeg på det

**Comment by GISAabenraa** [comment]
http://onedoor-test.aabenraa.dk/#/aabenraa/standard/plansystem/vedtagetlokalplan/1114270/ejerfortegnelse.EjerskaberForGeometriProvider_0

**Comment by rastermanden** [comment]
Har lavet eksempel på en med buffer (ejendommeForArealBuffer):
i din config.yml er der nu 3 faner med ejendomme. Kuin én skal vælges synes jeg. Du kan udkommentere eller slette dine detailhandlers. 

``` yaml
  plansystemsearcher:
    _ref: $.core.dk.plansystemsearcher
    detailhandlers:
      - _ref: $.core.dk.planInfoProvider
      - _ref: $.datafordeler.ejendommeForAreal
      - _ref: $.datafordeler.ejendommeForArealBuffer
      - _ref: $.ejerservice.EjerskaberForGeometriProvider
``` 

Den nye handler finder du i filen datafordeler.yml


```yaml
  ejendommeForArealBuffer:
    _type: s3.SqDetailsHandler
    _options:
      polygonIntersectsBuffer: -2
      buttonText: "Ejendomme (buffer)"
    searchers:
      - _ref: "$.datafordeler.ejendomssearcher"

```
