### ISSUE TITLE
Husnummervisning i kort fejler

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#65]
Visningen af husnumre i kortet fejler hos os. Det har stået på i noget tid, så det er ikke en tilfældig fejl.

I øvrigt er det noget rod, at det hedder _Adresser_ i det "lille" kort men _Husnumre_, hvis man skifter til kortvisning.

Vh Lars

**Comment by rastermanden** [comment]
Skyldes at WMS tjenesten ikke længere understøtter SLD.

i roden af sitet findes filen style.yml


Her kan du fjerne "params" delen

```yaml
  - source: Dawa
    type: adresse
    layer:
      zIndex: 999
      maxResolution: 1
      type: WMS
      host: https://kort.aws.dk/geoserver/aws4/wms
      params:
        STYLES: onedoor
        sld: https://septima.dk/widget/data/sld/dawa.xml
      crossOrigin: anonymous
      layer_name: aws4:adgangsadresser
      format: image/png
      singleTile: true
      visible: false
    style:
      strokecolor: 'rgba(0,70,132,1)'
      fillcolor: 'rgba(0,134,170,0.25)'
      svg: '<svg preserveAspectRatio="xMidYMid meet" width="16px" height="16px" viewBox="0 0 13 17" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><!-- Generator: Sketch 53.2 (72643) - https://sketchapp.com --><title>Combined Shape</title><desc>Created with Sketch.</desc><g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><path d="M6.46119625,0.579832479 C9.99581865,0.579832479 12.8611962,3.4405607 12.8611962,6.9694478 C12.8611962,11.7616593 6.46119625,16.5798325 6.46119625,16.5798325 C6.46119625,16.5798325 0.0611962467,11.7616593 0.0611962467,6.9694478 C0.0611962467,3.4405607 2.92657385,0.579832479 6.46119625,0.579832479 Z M6.47159781,9.46872137 C7.8484072,9.46872137 8.96453174,8.35440786 8.96453174,6.97983248 C8.96453174,5.6052571 7.8484072,4.49094359 6.47159781,4.49094359 C5.09478841,4.49094359 3.97866387,5.6052571 3.97866387,6.97983248 C3.97866387,8.35440786 5.09478841,9.46872137 6.47159781,9.46872137 Z" id="Combined-Shape" fill="currentColor" fill-rule="nonzero"></path></g></svg>'
  
```



I samme fil konfigureres de små kort og her kan ,man også selv ændre lagnavne 


``` yaml
    - id: adresse
      name: Adresser
      visible: false
      type: WMS
      host: https://kort.aws.dk/geoserver/aws4/wms
      params:
        STYLES: onedoor
        sld: https://septima.dk/widget/data/sld/dawa.xml
      crossOrigin: anonymous
      layer_name: aws4:adgangsadresser
      format: image/png
      singleTile: true


```
