### ISSUE TITLE
Måleværktøj i fuldskærmskort i OneDoor

### ISSUE THREAD

**Issue by furesoe** [Septima/OneDoor#67]
~~@klavspc~~
@rastermanden

Er det muligt at konfigurere fuldskærmskortet, så man kan få måleværktøjer? Både længder og arealer?

**Comment by rastermanden** [comment]
Man kan tilføje "measure" control i sin style.yml

```yml
        controls:
        - layertoggle:
            disable: false
            className: widget-control-position-lr
            layers:
             - "orto"
             - "standard"
        - layerswitch:
            layers: all
            excludeLayers:
            - dybde
            - plansystem_byggefelt
            - plansystem_delområde
            - plansystem_regionplan
            - orto
            - standard
            - Kortforsyningen_postdistrikter
            - Kortforsyningen_politikredse
            - baselayer1
            - itemsLayer
            - resultLayer
            - drawLayer
            - selectLayer
            showbuttons: true
            showlegend: true
            showheader: true
        - measure:
            disable: false
            debug: false
            modify: true
            features_style:
            - icon:
              symbol: circle
              radius: 5
              strokecolor: rgba(0,0,0,0.5)
              strokewidth: 2
            - icon:
              fillcolor: rgba(255,255,255,0.5)
              strokecolor: rgba(255,255,255,1)
              strokewidth: 2
              lineDash:
              - 5
              - 10
            buttons:
            - text: Mål afstand
              type: LineString
            - text: Mål areal
              type: Polygon
```
