### ISSUE TITLE
Addresser på Husnummer - fejl

### ISSUE THREAD

**Issue by GISAabenraa** [Septima/OneDoor#74]
Efter man har søgt på husnummer og gået videre i fanen "Adresser på Husnummeret" (Septima.Search.AdresserForHusnummerProvider_0)

ved at trykke på selve adressen
 ![image](https://github.com/Septima/OneDoor/assets/115632878/58b4c076-671c-4e5c-af93-3153660a2398)
 kommer der følgende fejl :

**Unexpected error**
Cannot resolve type for source fkg and typeId t_5710_born_skole_dis_t

**Comment by rastermanden** [comment]
Der kan være en fejl i din lokal integration. Vi kan se på det

**Comment by Ellebjerg** [comment]
Vi får også fejl ved adresser på husnummer
Unexpected error
Cannot resolve type for source DAF and typeId bbr_enhed

**Comment by rastermanden** [comment]
Der manglede noget konfiguratioen 

i datafordeler.yml

```yml

datafordeler:
  enhedssearcher:
    _type: datafordeler.EnhedsSearcher
    _options:
      fetcher:
        _ref: "$.datafordeler.fetcher"
```

I config.yml skal seacer tilføjes:

```yml

```controller:
  _type: Septima.Search.Controller
  _options:
    blankBehavior: search
  searchers:
    - _ref: $.searchers.dawa
    - _ref: "$.datafordeler.enhedssearcher"

**Comment by rastermanden** [comment]
> Vi får også fejl ved adresser på husnummer Unexpected error Cannot resolve type for source DAF and typeId bbr_enhed

Løst i andet issue

**Comment by rastermanden** [comment]
Der manglede af ukendt årsag en fkgsearcher i _controlleren_
``` yml
controller:
  _type: Septima.Search.Controller
  _options:
    blankBehavior: search
  searchers:
    - _ref: $.searchers.dawa
    - _ref: $.searchers.plansystemsearcher
    - _ref: $.searchers.cvr
    - _ref: $.ejendomsperspektiv.ejendomssearcher
    - _ref: $.ejendomsperspektiv.bygningssearcher
    - _ref: $.core.dk.geostednavnsearcher
    - _ref: $.searchers.geosearcher
    - _ref: $.tinglysning.geoPartnerSearcher
    - _ref: "$.searchers.geometrysearcher" # kun til geografiske opslag
    - _ref: $.searchers.enhedssearcher
    - _ref: $.searchers.fkgsearcher
```
Nu har du Skoledistrikter både på husnummer og adresse (i test)

![image](https://github.com/Septima/OneDoor/assets/1125134/e7383cd2-6a0f-4869-93bc-b676ca7d0b62)
